### ISSUE TITLE
How does it differ from the Theseus project of Brackets?

### ISSUE THREAD

**Issue by FezVrasta** [willyelm/atom-bugs#2]
I've asked on Medium but probably is better here:

How does it differ from the Theseus project of Brackets?
https://github.com/adobe-research/theseus

At first glance seems like you could have reused their work and worked just on the Atom extension instead of rewrite everything, why isn't the case?

**Comment by willyelm** [comment]
It was not my intention to use Theseus from the beginning, I've already checked the existing debugger projects, just using the chrome and v8 protocol is fair enough to me instead reusing code was not originally created to work for a specific application. I am pretty sure Theseus does not count with functions and values I am expecting for like, since I want a simple debugger, if you see the source code is lightweight, I could have spent some days to study and understand other debugger project and try to port it to atom, but took that time to build my own implementation, which is not completed yet. so bottom line I don't see a reason why to use Theseus.

If you have a good reason why use Theseus I could write a port for atom in my free time. Thanks for the feedback!

**Comment by FezVrasta** [comment]
I've not strong arguments, they just seem really similar and I was wondering the "why" behind this one.
